export const roomConstants = {
  GET_ROOMS_REQUEST: 'GET_ROOMS_REQUEST',
  GET_ROOMS_SUCCESS: 'GET_ROOMS_REQUEST',
  GET_ROOMS_FAILURE: 'GET_ROOMS_REQUEST',

  ADD_ROOM_REQUEST: 'ADD_ROOM_REQUEST',
  ADD_ROOM_SUCCESS: 'ADD_ROOM_SUCCESS',
  ADD_ROOM_FAILURE: 'ADD_ROOM_FAILURE',

  JOIN_ROOM_REQUEST: 'JOIN_ROOM_REQUEST',
  JOIN_ROOM_SUCCESS: 'JOIN_ROOM_SUCCESS',
  JOIN_ROOM_FAILURE: 'JOIN_ROOM_FAILURE',

  LEAVE_ROOM_REQUEST: 'LEAVE_ROOM_REQUEST',
  LEAVE_ROOM_SUCCESS: 'LEAVE_ROOM_SUCCESS',
  LEAVE_ROOM_FAILURE: 'LEAVE_ROOM_FAILURE'
}